=== api-evangelist/azure-test-labs/json-schema/azure-test-labs-artifact-source-properties-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/azure-test-labs/refs/heads/main/json-schema/azure-test-labs-artifact-source-properties-schema.json",
  "title": "ArtifactSourceProperties",
  "description": "Properties of an artifact source.",
  "type": "object",
  "properties": {
    "armTemplateFolderPath": {
      "description": "The folder containing Azure Resource Manager templates.",
      "type": "string"
    },
    "branchRef": {
      "description": "The artifact source's branch reference.",
      "type": "string"
    },
    "createdDate": {
      "description": "The artifact source's creation date.",
      "format": "date-time",
      "readOnly": true,
      "type": "string"
    },
    "displayName": {
      "description": "The artifact source's display name.",
      "type": "string"
    },
    "folderPath": {
      "description": "The folder containing artifacts.",
      "type": "string"
    },
    "provisioningState": {
      "description": "The provisioning status of the resource.",
      "readOnly": true,
      "type": "string"
    },
    "securityToken": {
      "description": "The security token to authenticate to the artifact source.",
      "type": "string"
    },
    "sourceType": {
      "description": "The artifact source's type.",
      "enum": [
        "VsoGit",
        "GitHub"
      ],
      "type": "string",
      "x-ms-enum": {
        "modelAsString": true,
        "name": "SourceControlType"
      }
    },
    "status": {
      "description": "Indicates if the artifact source is enabled (values: Enabled, Disabled).",
      "enum": [
        "Enabled",
        "Disabled"
      ],
      "type": "string",
      "x-ms-enum": {
        "modelAsString": true,
        "name": "EnableStatus"
      }
    },
    "uniqueIdentifier": {
      "description": "The unique immutable identifier of a resource (Guid).",
      "readOnly": true,
      "type": "string"
    },
    "uri": {
      "description": "The artifact source's URI.",
      "type": "string"
    }
  }
}

=== api-evangelist/azure-test-labs/examples/azure-test-labs-artifact-source-properties-example.json
{
  "armTemplateFolderPath": "example-string",
  "branchRef": "example-string",
  "createdDate": "2026-04-19T12:00:00Z",
  "displayName": "example-string",
  "folderPath": "example-string",
  "provisioningState": "example-string",
  "securityToken": "example-string",
  "sourceType": "VsoGit",
  "status": "Enabled",
  "uniqueIdentifier": "example-string",
  "uri": "example-string"
}
